# Generated by Django 5.0.1 on 2024-02-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchtable',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
