# Generated by Django 5.0.1 on 2024-02-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pitchtable_price_alter_usertable_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchtable',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
