# Generated by Django 5.0.1 on 2024-02-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pitchtable_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admintable',
        ),
    ]
