# Generated by Django 5.0.1 on 2024-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_admintable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='paymentid',
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bookingtable',
            name='phonenumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
