# Generated by Django 5.0.1 on 2024-02-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_bookingtable_paymentid_bookingtable_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitchtable',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pitchtable',
            name='time',
        ),
        migrations.AddField(
            model_name='pitchtable',
            name='phonenumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
