# Generated by Django 5.0.1 on 2024-02-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_pitchtable_date_remove_pitchtable_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchtable',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
