# Generated by Django 5.0.1 on 2024-02-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_pitchtable_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='brand',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
