# Generated by Django 5.0.1 on 2024-02-29 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_itemtable_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='productimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.itemtable')),
            ],
        ),
    ]
