# Generated by Django 5.0.1 on 2024-03-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttable',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
