# Generated by Django 5.0.1 on 2024-03-07 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_carttable_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='turfimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('turfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pitchtable')),
            ],
        ),
    ]
