# Generated by Django 5.0.1 on 2024-03-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_turfimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carttable',
            name='date',
        ),
        migrations.RemoveField(
            model_name='carttable',
            name='time',
        ),
    ]
