# Generated by Django 5.0.1 on 2024-03-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_carttable_date_remove_carttable_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carttable',
            old_name='amount',
            new_name='total',
        ),
        migrations.AddField(
            model_name='carttable',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
