# Generated by Django 5.0.1 on 2024-03-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_amount_carttable_total_carttable_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carttable',
            name='price',
        ),
    ]
