# Generated by Django 5.0.1 on 2024-03-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_ordertable_cartid_remove_ordertable_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='time',
        ),
    ]
