# Generated by Django 5.0.1 on 2024-03-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_ordertable_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
