# Generated by Django 5.0.1 on 2024-03-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_ordertable_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttable',
            name='orderid',
            field=models.IntegerField(null=True),
        ),
    ]
