# Generated by Django 5.0.1 on 2024-03-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_carttable_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='paymentmode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
