# Generated by Django 5.0.1 on 2024-03-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_ordertable_paymentmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='totalbill',
            field=models.FloatField(null=True),
        ),
    ]
