# Generated by Django 5.0.1 on 2024-03-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_ordertable_totalbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttable',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
