# Generated by Django 5.0.1 on 2024-03-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_carttable_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carttable',
            old_name='status',
            new_name='cartstatus',
        ),
    ]
