# Generated by Django 5.0.1 on 2024-03-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_status_carttable_cartstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='paymentmode',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='totalbill',
        ),
    ]
