# Generated by Django 5.0.1 on 2024-03-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_ordertable_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='paymentmode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='phonenumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='totalbill',
            field=models.FloatField(null=True),
        ),
    ]
