# Generated by Django 5.0.1 on 2024-03-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_ordertable_address_ordertable_paymentmode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttable',
            name='cartstatus',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='carttable',
            name='orderid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
