# Generated by Django 5.0.1 on 2024-03-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_carttable_cartstatus_alter_carttable_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
