# Generated by Django 5.0.1 on 2024-03-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_feedbacktable_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
