# Generated by Django 5.0.1 on 2024-03-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_feedbacktable_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktable',
            name='itemid',
        ),
        migrations.RemoveField(
            model_name='feedbacktable',
            name='pitchid',
        ),
    ]
