# Generated by Django 5.0.1 on 2024-03-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_feedbacktable_userid_feedbacktable_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintable',
            name='itemid',
        ),
        migrations.RemoveField(
            model_name='complaintable',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='complaintable',
            name='pitchid',
        ),
    ]
