# Generated by Django 5.0.1 on 2024-03-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_complaintable_itemid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintable',
            name='subject',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='complaintable',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='complaintable',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
