# Generated by Django 5.0.1 on 2024-03-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_complaintable_subject_alter_complaintable_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintable',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
