# Generated by Django 5.0.1 on 2024-03-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_complaintable_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='paymenttable',
        ),
    ]
