# Generated by Django 5.0.1 on 2024-03-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_ordertable_datetime_delete_paymenttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
