# Generated by Django 5.0.1 on 2024-03-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_bookingtable_paymentmode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtable',
            name='status',
        ),
    ]
